"use client"
import Header from "@/app/components/Header";
import { SessionProvider } from "next-auth/react";

/*
export const metadata: Metadata = {
  title: "mp-6",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <SessionProvider>
          <Header />
          {children}
      </SessionProvider>
      </body>
    </html>
  );
}
